### ISSUE TITLE
Combining axis.set_yscale with lineid_plot

### ISSUE THREAD

**Issue by Delosari** [phn/lineid_plot#8]
First I want to thank you for this very neat library.

Second I wonder if you could comment on how you can combine this lineid_plot() function with the set_yscale method. If I try to set a lower limit than the default the plotted text with the lines labels disappears (also if you do it manually)

Thanks a lot for your work!

**Comment by phn** [comment]
Hello,

Good to know that the library is helping you.

Could you post some code that replicates the issue you raise, so that I can experiment with it?

Regards,

Prasanth

**Comment by Delosari** [comment]
Thanks for the reply and sorry for the delay! 

This is a copy of one of your examples:
```
import numpy as np
from matplotlib import pyplot as plt
import lineid_plot

wave = 1240 + np.arange(300) * 0.1
flux = np.random.normal(size=300)

line_wave = [1242.80, 1260.42, 1264.74, 1265.00, 1265.2, 1265.3, 1265.35]
line_label1 = ['N V', 'Si II', 'Si II', 'Si II', 'Si II', 'Si II', 'Si II']

fig, ax = lineid_plot.plot_line_ids(wave, flux, line_wave, line_label1)
ax.set_ylim(top=1)
plt.show()
```

Which gives this: 
![example](https://user-images.githubusercontent.com/4238978/32759562-abc33748-c8af-11e7-8165-5ff3107ab29e.png)

Is there a way to force the text to labels to reaperar?

Thanks again

**Comment by phn** [comment]
Hello,

Thanks for the code. 

Seems like we can solve the issue if we change the library code so that it plot labels in axes coordinates. I will try to look deeper into this over the next weekend. 

Regards,
Prasanth

**Comment by Delosari** [comment]
Thank you very much.

(If you have a dirty solution that does not require you to change the library code I do not mind :)

**Comment by phn** [comment]
Hello,

I found that the easiest way to get around this problem is to call `lineid_plot.plot_line_ids` AFTER calling `ax.set_ylim`.

```python
import numpy as np
from matplotlib import pyplot as plt
import lineid_plot

wave = 1240 + np.arange(300) * 0.1
flux = np.random.normal(size=300)

line_wave = [1242.80, 1260.42, 1264.74, 1265.00, 1265.2, 1265.3, 1265.35]
line_label1 = ['N V', 'Si II', 'Si II', 'Si II', 'Si II', 'Si II', 'Si II']

# create plot and maipulate it before calling lineidplot
plt.plot(wave, flux)
ax = plt.gca() # current axes
ax.set_ylim(top=1)

# now call lineid, passing in axes.
lineid_plot.plot_line_ids(wave, flux, line_wave, line_label1, ax=ax)

plt.show()
```
![call_lineid_after_set_ylim](https://user-images.githubusercontent.com/280280/32978118-8f84ba38-cc61-11e7-9aea-9af5b5cde017.png)

If I get time (don't know when) I will try to add some functions into the library to adjust locations after they are plotted first time.

Hope this helps. 

Regards,
Prasanth

**Comment by Delosari** [comment]
Thanks a lot! That works great!

One last question: How should we cite the library?

**Comment by phn** [comment]
Hello,

You can cite this library as follows:

Nair, Prasanth Haridas. (2016, December 2). LineID Plot (Version 0.4). Zenodo. http://doi.org/10.5281/zenodo.1069584

Regards,
Prasanth
